---
all:
  children:
    windows:
      children:
        commons:
          hosts:
        servicehosts:
          hosts:
            server01:
              ansible_host: 192.168.1.189
            server02:
              ansible_host: 192.168.1.188
      vars:
        ansible_port: 5985
        ansible_connection: winrm
        ansible_winrm_scheme: http
        ansible_winrm_server_cert_validation: ignore
        ansible_become_method: runas