---
- name: Configure the site
  hosts: windows
  gather_facts: true

  tasks:
  - name: Apply Common configuration
    hosts: all
    roles:
      - common

  - name: Apply servicehost configuration
    hosts: servicehosts
    roles:
      - servicehost