---
- name: Set "Log on as a service" rights
  ansible.windows.win_user_right:
    name: SeServiceLogonRight
    action: add
    users: '{{ serviceaccountusername }}'

# Pulls windows service information and registers a variable; We technically check it in the next step
- name: Check existing service configuration
  ansible.windows.win_service_info:
    name: '{{ servicename }}'
  register: existingservice

# 'win_service' is capable of being idempotent, but not with the properties we're setting below
# Uses 'when:' to only run this when the account is not already set as the 'runas' account
- name: Set service runas acccount
  ansible.windows.win_service:
    name: '{{ servicename }}'
    start_mode: auto
    state: restarted
    update_password: always
    username: '{{ ansible_hostname }}\{{ serviceaccountusername }}'
    password: '{{ serviceaccountpassword }}'
  when: serviceaccountusername not in existingservice.services[0].username